version: '3.7'
services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        image: sampleapp-build-image
        container_name: sampleapp-build
        ports: 
            - "4000:4000"
        environment: 
            - MONGO_DB=sampleapp-prod
            - MONGO_HOSTNAME=mongo
            - MONGO_PORT=27017
            - NODE_ENV:production
        depends_on: 
            - mongo
        networks: 
            - sampleapp-production
    mongo:
        image: mongo
        volumes: 
            - data-volume:/data/db
        networks: 
            - sampleapp-production
        ports: 
            - "27017:27017"
        
networks: 
    sampleapp-production:
        driver: bridge

volumes: 
    data-volume:
    node_modules:
