version: '3.7'
services: 
    ui:
        build: 
            context: ./client
            dockerfile: Dockerfile
        stdin_open: true
        image: sampleapp-client-image
        container_name: sampleapp-client
        environment: 
            - CHOKIDAR_USEPOLLING=true
        networks: 
            - sampleapp-network
        volumes: 
            - ./client:/usr/app
            - /usr/app/node_modules
        ports: 
            - "3000:3000"
        depends_on:
            - api
    api:
        build: 
            context:  ./server
            dockerfile: Dockerfile
        image: sampleapp-server-image
        container_name: sampleapp-server
        ports: 
            - "8080:4000"
        networks: 
            - sampleapp-network
        volumes: 
            - ./server:/usr/app
            - /usr/app/node_modules
        depends_on:
            - mongo
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
            - MONGO_DB=sampleapp
            - MONGO_HOSTNAME=mongo
            - MONGO_PORT=27017
    mongo:
        image: mongo
        volumes: 
            - data-volume:/data/db
        networks: 
            - sampleapp-network
        ports: 
            - '27017:27017'
networks: 
    sampleapp-network:
        driver: bridge
volumes: 
    data-volume:
