version: '3'
services: 
    ui:
        build: 
            context: ./client
            dockerfile: Dockerfile
        stdin_open: true
        volumes: 
            - ./client:/usr/app
        ports: 
            - "3000:3000"
        depends_on:
            - api
    api:
        build: 
            context:  ./server
            dockerfile: Dockerfile
        ports: 
            - "8080:4000"
        volumes: 
            - ./server:/usr/app
        depends_on:
            - mongo
        environment: 
            - NODE_ENV=development
            - MONGO_DB=sampleapp
            - MONGO_HOSTNAME=mongo
            - MONGO_PORT=27017
    mongo:
        image: mongo
        ports: 
            - '27017:27017'